name: bus_time_table
description: Flutter aplikacija za prikaz voznih redov prevoznika Arriva

version: 2.0.4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.5
  dotted_line: ^3.1.0
  eva_icons_flutter: ^3.1.0
  flutter_bloc: ^8.1.2
  flutter_typeahead: ^4.3.7
  fluttertoast: ^8.2.1
  html: ^0.15.2
  http: ^0.13.5
  intl: ^0.17.0
  path_provider: ^2.0.13
  shared_preferences: ^2.0.18
  sliding_up_panel: ^2.0.0+1
  bloc: ^8.1.1
  meta: ^1.8.0
  url_launcher: ^6.1.10
  crypto: ^3.0.2

dev_dependencies:
  flutter_launcher_icons: ^0.12.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/postaje.txt
    - assets/images/
